version: '3'

services:
  entr_runtime:
    build:
      context: docker/.
      dockerfile: Dockerfile
    container_name: ENTR-runtime
    image: entr_runtime
    volumes:
      - ${analytics}:/home/jovyan/host/analytics
      - ${warehouse}:/home/jovyan/host/warehouse
    ports:
      - 8888:8888 # Jupyter notebook UI
      - 4040:4040 # [Spark Web UI](https://spark.apache.org/docs/latest/monitoring.html#web-interfaces)
