# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# Script from https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
#

name: Build and publish dev Docker image to Github container registry

on:
  push:
    branches: ['develop']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: entralliance/entr_runtime_dev:latest